# An example configfiguration file. 
# The values that are used for the optional keys correspond to their default values.

# (Optional)
[coordinator]
# (Optional) Address of the coordinator
host = "localhost"
# (Optional) Port of the coordinator
port = 50051

# (Optional)
[server.grpc_options] 
# More information about all available gRPC options can be found here: 
# https://grpc.github.io/grpc/cpp/group__grpc__arg__keys.html#ga813f94f9ac3174571dd712c96cdbbdc1

# Example:
# Maximum message length that the channel can receive. -1 means unlimited. 
# "grpc.max_receive_message_length" = -1

# (Required)
[storage]
# (Optional) See FIXME(XP-515) in "xain_sdk/participant_state_machine.py"
enable = false
# (Required) URL to the storage service to use
endpoint = "http://minio-dev:9000"
# (Required) Name of the bucket for storing the aggregated models
bucket = "xain-fl-aggregated-weights"
# (Required) AWS access key ID to use to authenticate to the storage service
access_key_id = "minio"
# (Required) AWS secret access to use to authenticate to the storage service
secret_access_key = "minio123"

# (Optional)
[logging]
# (Optional) The log level can be one of "notset", "debug", "info", "warning",
# "error" and "critical".
level = "info"
